### PR TITLE
Add cookie propagation configuration boolean

### PR DESCRIPTION
**Pull request by manithree**
There are times when it's useful to ignore cookies being sent from the server.

### CODE REVIEW

**Comment by fcsonline** [comment]
Sorry, for this late answer.

One rule I have been following in drill is to simulate the same behaviour as browsers. They send the cookies to the server all the time.

Can you explain when is this useful?

**Comment by manithree** [comment]
My particular case may not be generally applicable, but IIRC, I needed to
test out a token-based sticky session where the cookie-based sticky
wouldn't work because of CORS, but it was complicated to recreate the
customer's CORS situation and I couldn't turn off cookies on the load
balancer.

**Comment by fcsonline** [comment]
Reviewing the `request` code I can confirm that [default cookie header set](
https://github.com/fcsonline/drill/blob/master/src/actions/request.rs#L163) goes before custom headers. So, if this is your case, you are able to overwrite it:

```yaml
- name: Request ignoring cookies
  request:
    url: /counter
    headers:
      Cookie: ''
   assign: memory
```

**Comment by fcsonline** [comment]
The initial issue of this thread can be achieved without changing code as I described in my previous comment. I'm going to close it. Feel free to reopen the conversation.

**Pull request closed without merging**
