### PR TITLE
Migrate drill to async futures

### PR DESCRIPTION
**Pull request by fcsonline**

### CODE REVIEW

**Comment by otto-von-bivouac** [comment]
This looks like an awesome feature! Can we expect to get this merged anytime soon? :shipit:

**Comment by fcsonline** [comment]
This was coded before the stabilization of Rust async futures. I need to review all changes in hyper crate and adapt them here. I hope to merge this feature sooner than later. 🤞

**Comment by otto-von-bivouac** [comment]
It would be awesome to have this merged one way or another. Please let me know if I can be any help to move this forward.

We have created support in kubestone for drill with the hope that it can be the go-to benchmark for http load testing: https://github.com/xridge/kubestone/pull/109

**Comment by janus** [comment]
@fcsonline 
I noticed that this is multi-threaded, so where do you want to be replaced with async? I guess the multi-threaded part or changing IO to async.  Will this do, https://async.rs/blog/announcing-async-std/#? 

However, if you have a file in mine just let me know.

**Comment by fcsonline** [comment]
I created this PR to start using hyper async before the async futures was stable. Right now, the only missing part is to apply all required changes to start using the new async syntax.

**Comment by janus** [comment]
> I created this PR to start using hyper async before the async futures was stable. Right now, the only missing part is to apply all required changes to start using the new async syntax.

@fcsonline 
I noticed at least 3 branches with async in their names. Is branch async-final the correct one?

**Comment by janus** [comment]
With std::future::Future stabilizing in Rust 1.36, it is a goal to upgrade from futures@0.1 to std::future::Future in the next breaking change (hyper@0.13).

Am I allowed to use latest hyper,  (hyper@0.13)?

**Comment by fcsonline** [comment]
Yes, exactly. This PR is pointing to `feature/async-final` branch.

You can use the lastest hyper stable version as far as all features current features work.

**Comment by janus** [comment]
@fcsonline 
I have facing some  particularly converting  `hyper::Body` to Vec<u8>.  In your own concat2 was able to get that done ... but mine ... concat2 is no more available ....

**Comment by fcsonline** [comment]
@janus I don't know the details of the new hyper version.

**Comment by janus** [comment]
> @janus I don't know the details of the new hyper version.

I have resolved that one but I have another , sharing in between threads .

**Comment by fcsonline** [comment]
I know that is difficult to make all this work properly.

**Comment by janus** [comment]
> I know that is difficult to make all this work properly.

Sure!! But I don't want to give up easily it creates room for me to learn..

**Comment by awulkan** [comment]
What's the status on this? Did you run into any issues @janus?

**Comment by Dentrax** [comment]
Any updates? @fcsonline

**Comment by janus** [comment]
I will update later this week. Most of the libs were not using same future . This causes a lot of issues. However I will circle back on it this week, @fcsonline, @awulkan, @Dentrax

**Comment by patrick-armitage** [comment]
Very excited to see this merged to master, my org really wants to adopt drill for our new load test framework.  Any idea of an ETA on merge-readiness for this feature?  Thanks for all the hard work you guys!

**Comment by fcsonline** [comment]
Drill with async is finally here! :tada: Thanks to @messense for the awesome work!

**Pull request closed without merging**
