### PR TITLE
Fixed quotes in string fields and panic on HTTP errors

### PR DESCRIPTION
**Pull request by alexgavrushenko**
1. Issue #35 was caused by JSON Value ToString implementation, as only quoted string is a valid json value.
2. I was load-testing my service at highest rps, and when I got 404 or 500 errors drill panicked. I think 
better behaviour is to fail iteration and count failures. For now I handled this with making default "" value, but I can handle it better later

### CODE REVIEW

**Comment by d11-acummins** [comment]
Thank you for fixing the JSON quotes issue, it works great for us

**Comment by fcsonline** [comment]
Thanks for your contribution! :clap: 

I just merged manually the second part of your commit, the one about panics. About the first one, I took the opportunity to tweak it a bit.

Closing this PR.

**Comment by fcsonline** [comment]
I have been rethinking the behavior about missing interpolations and I'm not sure about defaulting to empty string if previous requests failed. It can induce a wrong URL construction with an unexpected result.

I think the best approach will be to add a new command flag to be opt-in for this behaviour.

**Comment by fcsonline** [comment]
I have created a new PR to handle this. https://github.com/fcsonline/drill/pull/45

**Pull request closed without merging**
